query Cart($input: CartInput!, $userId: String) {
    cart(cartInput: $input, userId: $userId) {
        total
        subTotal
        isDeductionsEligible
        discount
        coupon
        taxes {
            total
            breakup {
                title
                description
                amount
                percentage
                total
            }
        }
        products {
            id
            title
            slug
            salePrice
            retailPrice
            quantity
            total
        }
    }
}
